### PR TITLE
Update notebooks

### PR DESCRIPTION
**Pull request by tomkooij**
Minimale Inhoud, zoals besproken met jos:        
- [x] downloaden station
- [x] downloaden koincs
- [x] zoeken naat koincs
- [x] opvragen tijdkorrekties
- [x] ~~veranderen tijdkorrekties~~ Tijdcorrecties opgaven aan reconstructie class?!
- [x] opvragen stations- en detektor lokaties
- [x] ~~veranderen stations- en detektor lokaties~~
- [x] rekonstruktie station
- [x] rekonstruktie kluster

Extra inhoud:
- [x] een notebook 0 voor python uitleg
- [x] een recept "station map"

ToDo:
- [x] toevoegen inhoud (zie lijstje hierboven)
- [x] opdrachten in notebooks naast (of na) de uitleg.
- [x] notebooks in markdown via `notedown`
- [x] notebook conversion .md -> .ipynb for `make gh-pages`

### CODE REVIEW

**Comment by 153957** [comment]
Possible pre commit filters for IPython Notebooks:
http://stackoverflow.com/questions/18734739/using-ipython-notebooks-under-version-control

**Comment by tomkooij** [comment]
This can be merged.

An updated makefile that converts .md to .ipynb is included in this PR, but `index.html` needs some reordering.

**Comment by 153957** [comment]
Not quite ready yet!

**Comment by tomkooij** [comment]
Argh... I just deleted my comment...

Anyway. 'index.html` needs some reordering after merging this.

**Comment by 153957** [comment]
Your comment:

> This can be merged.
>
> An updated makefile that converts .md to .ipynb is included in this PR, but index.html needs some reordering.
> 
> I have merged this branch on /data/hisparc/tom/infopakket:
> 
> On lena/tevere:
> 
> cd /data/hisparc/tom/infopakket
> git checkout gh-pages
> irefox index.html &

**Comment by tomkooij** [comment]
> I viewed some notebooks, and encountered a problem with the hyperlinks:
> https://github.com/HiSPARC/infopakket/blob/notebooks/notebooks/3_zenith_afhankelijkheid.md
> 
> The links do not work because they contain a linebreak in the source code.
> I do not know if this is also a problem in the notebook version.

The hyperlink work in my original notebook.

But the notebooks are not converted correctly by the makefile.

**Comment by 153957** [comment]
By notedown you mean?
Perhaps report a bug there?

**Comment by tomkooij** [comment]
It's probably a bug in my makefille.

**Comment by 153957** [comment]
When I download the .md file (notebook 3) as is and use my local Markdown quick look viewer the links are broken in the same way as they are on GitHub.

**Comment by tomkooij** [comment]
Yes, links are broken in notebooks converted to .ipynb notedown as well. (\n in url) We need to file an issue.

**Comment by 153957** [comment]
https://github.com/aaren/notedown/issues/49

**Pull request merged**
