### PR TITLE
Add travis config to build and deploy infopakket.

### PR DESCRIPTION
**Pull request by 153957**
It works! It already deployed to the gh-pages branch successfully!
http://docs.hisparc.nl/infopakket/

The TexLive installation is cached to save time, it does update all installed TeX packages each runs.
A full new install takes less than 10 minutes if the cache is ever invalidated. All documentation and sources are not installed for TeX packages, saving a lot of space and time. There are still a lot more packages that could be removed to save some space, but it takes some time to figure out the precise requirements (todo.. maybe).
 
Todo:
- [x] Exit with error if one of the PDFs fails to be generated (i.e. do not deploy!)
- [ ] Get more log/error output from latexmk IF there is an error..
- [ ] Perhaps automated zip creation for recepten (they do include files not in this repo..).
- [x] Add shield to README

### CODE REVIEW

**Comment by 153957** [comment]
Note: the strange 'deployed at ...' file is created by Travis, will probably be resolved in future: https://github.com/travis-ci/dpl/issues/696

**Comment by 153957** [comment]
Can probably also be used for RouteNet.

**Comment by tomkooij** [comment]
Wow! nice work.

**Comment by davidfokkema** [comment]
Wonderful, thanks!

**Pull request merged**
